### ISSUE TITLE
HEVC/x265 videos are rated at poorer quality than they should be

### ISSUE THREAD

**Issue by psouza4** [psouza4/mediacentermaster#1818]
The general quality rating Media Center Master determines for a video seems poorer than it should be for HEVC/x265 videos, mostly due to their more efficient and lower video bitrates.

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.18 build 9618.773 (2.18.9618.773).

**Comment by Jackeldk** [comment]
it dosent seem to have fixed it yet

**Comment by psouza4** [comment]
"fixed" is entirely relative.  You may want to tell me what kind of rating you're expecting to see with what kind of video details.  Simply having an x265 video won't skyrocket its quality rating to 100% as there are other factors such as resolution, bitrate, framerate, audio quality, etc. to consider.

What changed was the algorithm that calculates this quality rating lets the x265 codec get higher ratings with lower bitrates than x264 or other codecs because it's literally a high-efficiency codec.

**Comment by syntax53** [comment]
This is definitely still not fixed.  I just got into 4k movies and everything I've put in my library so far has been listed at sub-60 quality ratings.  Even those at 4k HDR 18 Mbps, 7.1 TrueHD will show 53 quality.

```
<?xml version="1.0" encoding="utf-8"?>
<Title>
	<LocalTitle>Minions</LocalTitle>
	<OriginalTitle>Minions</OriginalTitle>
	<ProductionYear>2015</ProductionYear>
	<Added>12/15/2018 7:47:49 PM</Added>
	<IMDBrating>6.4</IMDBrating>
	<ContentRating>PG</ContentRating>
	<MPAARating>PG</MPAARating>
	<IMDB>tt2293640</IMDB>
	<IMDbId>tt2293640</IMDbId>
	<TMDbId>211672</TMDbId>
	<Budget>74000000</Budget>
	<Revenue>1156730962</Revenue>
	<Language>English</Language>
	<LanguageCode>en</LanguageCode>
	<Country>US</Country>
	<RunningTime>91</RunningTime>
	<Overview>Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.</Overview>
	<Genres>
		<Genre>Animation</Genre>
	</Genres>
	<Studios>
		<Studio>Illumination Entertainment</Studio>
		<Studio>Universal Pictures</Studio>
	</Studios>
	<Persons>
		<Person>
			<Name>Sandra Bullock</Name>
			<Type>Actor</Type>
			<Role>Scarlet Overkill (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/bsAy8f8UZKairXQzRukU5FP4XAQ.jpg</Image>
		</Person>
		<Person>
			<Name>Jon Hamm</Name>
			<Type>Actor</Type>
			<Role>Herb Overkill (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/wb14AA6u8dqA0XNweRIeKXatzzc.jpg</Image>
		</Person>
		<Person>
			<Name>Michael Keaton</Name>
			<Type>Actor</Type>
			<Role>Walter Nelson (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/baeHNv3qrVsnApuKbZXiJOhqMnw.jpg</Image>
		</Person>
		<Person>
			<Name>Allison Janney</Name>
			<Type>Actor</Type>
			<Role>Madge Nelson (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/cDcB8mKP1GiIeoM3Qe7GIucs0iv.jpg</Image>
		</Person>
		<Person>
			<Name>Steve Coogan</Name>
			<Type>Actor</Type>
			<Role>Professor Flux / Tower Guard (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/tT7OXc2qA6hlREHXdwGLp0XihzA.jpg</Image>
		</Person>
		<Person>
			<Name>Jennifer Saunders</Name>
			<Type>Actor</Type>
			<Role>Reine Elizabeth II (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/c1qRVTYqUhWd7y2ws426zdyqhln.jpg</Image>
		</Person>
		<Person>
			<Name>Geoffrey Rush</Name>
			<Type>Actor</Type>
			<Role>Narrator (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/npXFjaFQzBNroCEPllGPTZ5IisA.jpg</Image>
		</Person>
		<Person>
			<Name>Steve Carell</Name>
			<Type>Actor</Type>
			<Role>Gru (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/37ukZmvCfWIb5oXoijtzQq6pTQV.jpg</Image>
		</Person>
		<Person>
			<Name>Pierre Coffin</Name>
			<Type>Actor</Type>
			<Role>Stuart, Kevin And Bob (voices)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/enSQNAwRSDPq9M9VZ1yjDwKWbev.jpg</Image>
		</Person>
		<Person>
			<Name>Katy Mixon</Name>
			<Type>Actor</Type>
			<Role>Tina (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/o6yDzpvqsq0bObKDGPQdoszRKyW.jpg</Image>
		</Person>
		<Person>
			<Name>Michael Beattie</Name>
			<Type>Actor</Type>
			<Role>VNC Announcer / Walter Jr. (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/gDuLXdt6xXMjGOmdqoLymyra55n.jpg</Image>
		</Person>
		<Person>
			<Name>Hiroyuki Sanada</Name>
			<Type>Actor</Type>
			<Role>Sumo (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/fljn2lkeej3gAwSOvXXMVVQlA2K.jpg</Image>
		</Person>
		<Person>
			<Name>Dave Rosenbaum</Name>
			<Type>Actor</Type>
			<Role>Fabrice (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/ajYL0iMlODjVhqukwIM9UuDzCyv.jpg</Image>
		</Person>
		<Person>
			<Name>Alex Dowding</Name>
			<Type>Actor</Type>
			<Role>Royal Advisor (voice)</Role>
			<Image />
		</Person>
		<Person>
			<Name>Paul Thornley</Name>
			<Type>Actor</Type>
			<Role>News Reporter (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/4leB3psu55AaGGWxoPEf63wzUnX.jpg</Image>
		</Person>
		<Person>
			<Name>Kyle Balda</Name>
			<Type>Actor</Type>
			<Role>Additional Voices (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/jR8iAP6uC0V42KbUG87qBIUO3Hj.jpg</Image>
		</Person>
		<Person>
			<Name>Ava Acres</Name>
			<Type>Actor</Type>
			<Role>Additional Voices (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/kIK6BDTgMmNSAncCgZ7XQhFo5oZ.jpg</Image>
		</Person>
		<Person>
			<Name>Sherry Lynn</Name>
			<Type>Actor</Type>
			<Role>Additional Voices (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/kQDSC2z7sb6S5HcpOH6cmeJokKE.jpg</Image>
		</Person>
		<Person>
			<Name>Mickie McGowan</Name>
			<Type>Actor</Type>
			<Role>Additional Voices (voice)</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/k7TjJBfINsg8vLQxJwos6XObAD6.jpg</Image>
		</Person>
	</Persons>
	<Awards>Nominated for 1 BAFTA Film Award. Another 4 wins &amp; 24 nominations.</Awards>
	<BackdropURL>http://image.tmdb.org/t/p/original/iBvD5wzkghyTFDvq45sUDVmBsA9.jpg</BackdropURL>
	<Director>Kyle Balda</Director>
	<FullCertifications>Argentina:Atp, Australia:PG, Austria:6, Belgium:KT/EA, Brazil:Livre, Canada:PG, Canada:G, Chile:TE, Czech Republic:U, Denmark:7, Finland:K-8/5, France:Tous publics, Germany:0, Greece:K, Hong Kong:I, Hungary:12, Iceland:L, India:U, Indonesia:SU, Ireland:G, Italy:T, Japan:G, Malaysia:P13, Mexico:AA, Netherlands:6, New Zealand:PG, Norway:A, Philippines:PG-13, Poland:7, Portugal:M/6, Puerto Rico:PG, Russia:6+, Singapore:PG, South Africa:PG, South Korea:All, Spain:A, Sweden:7, Switzerland:6, Thailand:G, United Kingdom:U, United States:TV-G, United States:TV-PG, United States:PG</FullCertifications>
	<FormalMPAA>Rated PG for action and rude humor</FormalMPAA>
	<Votes>186036</Votes>
	<Synopsis>Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.</Synopsis>
	<Plot>Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.</Plot>
	<Outline>Minions Stuart, Kevin, and Bob are recruited by Scarlet Overkill, a supervillain who, alongside her inventor husband Herb, hatches a plot to take over the world.</Outline>
	<ShortDescription>Minions Stuart, Kevin, and Bob are recruited by Scarlet Overkill, a supervillain who, alongside her inventor husband Herb, hatches a plot to take over the world.</ShortDescription>
	<PosterURL>http://image.tmdb.org/t/p/original/q0R4crx2SehcEEQEkYObktdeFy.jpg</PosterURL>
	<Tagline>Before Gru, they had a history of bad bosses</Tagline>
	<Taglines>
		<Tagline>Before Gru, they had a history of bad bosses</Tagline>
	</Taglines>
	<Top250></Top250>
	<TrailerURL>http://www.youtube.com/watch?v=jc86EFjLFV4</TrailerURL>
	<Website>http://www.minionsmovie.com/</Website>
	<ReleaseDate>2015-06-17</ReleaseDate>
	<WritersList>Ken Daurio|Brian Lynch|Cinco Paul</WritersList>
	<Popularity>9.629</Popularity>
	<VoteCount>6812</VoteCount>
	<TMDbCollectionId>544669</TMDbCollectionId>
	<CollectionNumber>544669</CollectionNumber>
	<CollectionName>Minions</CollectionName>
	<Tags>
		<Tag>assistant</Tag>
		<Tag>aftercreditsstinger</Tag>
		<Tag>duringcreditsstinger</Tag>
		<Tag>evil mastermind</Tag>
		<Tag>minions</Tag>
		<Tag>3d</Tag>
	</Tags>
	<SimilarMovies>
		<SimilarMovie>Despicable Me</SimilarMovie>
		<SimilarMovie>Despicable Me 2</SimilarMovie>
		<SimilarMovie>Arthur Christmas</SimilarMovie>
		<SimilarMovie>Minions: Competition</SimilarMovie>
		<SimilarMovie>The Devil Wears Prada</SimilarMovie>
		<SimilarMovie>Minions: Cro Minion</SimilarMovie>
		<SimilarMovie>300: Rise of an Empire</SimilarMovie>
		<SimilarMovie>300</SimilarMovie>
		<SimilarMovie>Set It Up</SimilarMovie>
		<SimilarMovie>Land of the Lost</SimilarMovie>
		<SimilarMovie>Young Frankenstein</SimilarMovie>
		<SimilarMovie>Banana</SimilarMovie>
		<SimilarMovie>Minions: Orientation Day</SimilarMovie>
		<SimilarMovie>Home Makeover</SimilarMovie>
		<SimilarMovie>Minions: 3 Mini-Movie Collection</SimilarMovie>
		<SimilarMovie>Casper's Haunted Christmas</SimilarMovie>
		<SimilarMovie>Little Shop of Horrors</SimilarMovie>
		<SimilarMovie>Mower Minions</SimilarMovie>
	</SimilarMovies>
	<OtherID_RottenTomatoes></OtherID_RottenTomatoes>
	<RottenTomatoesId></RottenTomatoesId>
	<CriticRating></CriticRating>
	<CriticRatingSummary></CriticRatingSummary>
	<IMDB_ID>tt2293640</IMDB_ID>
	<TMDB>211672</TMDB>
	<TMDB_ID>211672</TMDB_ID>
	<Rating>6.4</Rating>
	<certification>PG</certification>
	<Trailer>http://www.youtube.com/watch?v=jc86EFjLFV4</Trailer>
	<Runtime>91</Runtime>
	<Description>Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.</Description>
	<PremiereDate>2015-06-17</PremiereDate>
	<VideoAspect>1.85:1</VideoAspect>
	<VideoBitrate>18412000</VideoBitrate>
	<VideoCodec>HEVC</VideoCodec>
	<VideoCodecType>HEVC</VideoCodecType>
	<VideoCodecRaw>HEVC</VideoCodecRaw>
	<VideoFileSize>16639539886</VideoFileSize>
	<VideoHeight>2076</VideoHeight>
	<VideoLength>91</VideoLength>
	<VideoLengthSeconds>5456</VideoLengthSeconds>
	<VideoQuality>Superior (4K UHD)</VideoQuality>
	<VideoWidth>3840</VideoWidth>
	<AudioBitrate>5247281</AudioBitrate>
	<AudioChannels>7.1</AudioChannels>
	<AudioCodec>TRUEHD</AudioCodec>
	<AudioCodecRaw>TRUEHD</AudioCodecRaw>
	<AudioFrequency>48000</AudioFrequency>
	<AspectRatio>1.85:1</AspectRatio>
	<MediaInfo>
		<Video>
			<Codec>HEVC</Codec>
			<FFCodec>HEVC</FFCodec>
			<BitRate>18412000</BitRate>
			<Height>2076</Height>
			<Width>3840</Width>
			<FrameRate>23.976</FrameRate>
			<Duration>91</Duration>
			<DurationSeconds>5456</DurationSeconds>
			<ScanType>Progressive</ScanType>
		</Video>
		<Audio>
			<Codec>TRUEHD</Codec>
			<FFCodec>TRUEHD</FFCodec>
			<Channels>8</Channels>
			<BitRate>5247281</BitRate>
			<Language>eng</Language>
		</Audio>
	</MediaInfo>
	<VideoHasSubtitles>True</VideoHasSubtitles>
	<Type></Type>
</Title>
```

```
<?xml version="1.0" encoding="utf-8"?>
<Title>
	<LocalTitle>The Matrix</LocalTitle>
	<OriginalTitle>The Matrix</OriginalTitle>
	<ProductionYear>1999</ProductionYear>
	<Added>12/2/2018 1:01:12 PM</Added>
	<IMDBrating>8.7</IMDBrating>
	<ContentRating>R</ContentRating>
	<MPAARating>R</MPAARating>
	<IMDB>tt0133093</IMDB>
	<IMDbId>tt0133093</IMDbId>
	<TMDbId>603</TMDbId>
	<Budget>63000000</Budget>
	<Revenue>463517383</Revenue>
	<Language>English</Language>
	<LanguageCode>en</LanguageCode>
	<Country>AU</Country>
	<RunningTime>136</RunningTime>
	<Overview>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</Overview>
	<Genres>
		<Genre>Action</Genre>
	</Genres>
	<Studios>
		<Studio>Village Roadshow Pictures</Studio>
		<Studio>Groucho II Film Partnership</Studio>
		<Studio>Silver Pictures</Studio>
		<Studio>Warner Bros. Pictures</Studio>
	</Studios>
	<Persons>
		<Person>
			<Name>Keanu Reeves</Name>
			<Type>Actor</Type>
			<Role>Thomas A. Anderson / Neo</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/bOlYWhVuOiU6azC4Bw6zlXZ5QTC.jpg</Image>
		</Person>
		<Person>
			<Name>Laurence Fishburne</Name>
			<Type>Actor</Type>
			<Role>Morpheus</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/8suOhUmPbfKqDQ17jQ1Gy0mI3P4.jpg</Image>
		</Person>
		<Person>
			<Name>Carrie-Anne Moss</Name>
			<Type>Actor</Type>
			<Role>Trinity</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/8iATAc5z5XOKFFARLsvaawa8MTY.jpg</Image>
		</Person>
		<Person>
			<Name>Hugo Weaving</Name>
			<Type>Actor</Type>
			<Role>Agent Smith</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/ysED1kp94bpnweNVaDoVQQ6iy8X.jpg</Image>
		</Person>
		<Person>
			<Name>Joe Pantoliano</Name>
			<Type>Actor</Type>
			<Role>Cypher</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/zBvDX2HWepvW9im6ikgoyOL2Xj0.jpg</Image>
		</Person>
		<Person>
			<Name>Gloria Foster</Name>
			<Type>Actor</Type>
			<Role>Oracle</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/8peApNX6ms84dK07Xguf84CNFJK.jpg</Image>
		</Person>
		<Person>
			<Name>Marcus Chong</Name>
			<Type>Actor</Type>
			<Role>Tank</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/nSffTYbV945Q1qdJHx9kmSfsMA7.jpg</Image>
		</Person>
		<Person>
			<Name>Paul Goddard</Name>
			<Type>Actor</Type>
			<Role>Agent Brown</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/4OalonKRAdZhXreaDWig3bZkELo.jpg</Image>
		</Person>
		<Person>
			<Name>Robert Taylor</Name>
			<Type>Actor</Type>
			<Role>Agent Jones</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/aqRJQj0KBPhGLDxfmOAXCUzCcSJ.jpg</Image>
		</Person>
		<Person>
			<Name>Julian Arahanga</Name>
			<Type>Actor</Type>
			<Role>Apoc</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/jFNdkOB6UhQEsN5Bo5Q5d2qT9YX.jpg</Image>
		</Person>
		<Person>
			<Name>Belinda McClory</Name>
			<Type>Actor</Type>
			<Role>Switch</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/kH5KJ0QuSN2MgYqRP4JSdnCcE9K.jpg</Image>
		</Person>
		<Person>
			<Name>Anthony Ray Parker</Name>
			<Type>Actor</Type>
			<Role>Dozer</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/2mMPyDmhPlW1HGIMJVpuZAYA3TP.jpg</Image>
		</Person>
		<Person>
			<Name>Matt Doran</Name>
			<Type>Actor</Type>
			<Role>Mouse</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/movt7tOlmzrlDbUIIiYdV9UemyK.jpg</Image>
		</Person>
		<Person>
			<Name>Ada Nicodemou</Name>
			<Type>Actor</Type>
			<Role>DuJour</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/zkgw0AuxuLe7UaNRWVjUNeFs3gI.jpg</Image>
		</Person>
		<Person>
			<Name>David Aston</Name>
			<Type>Actor</Type>
			<Role>Rhineheart</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/aO7w5K2BjeQaAUN3ogo9NuAD1qI.jpg</Image>
		</Person>
		<Person>
			<Name>Marc Aden Gray</Name>
			<Type>Actor</Type>
			<Role>Choi</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/h42Zd2L1srUxw1VihY1fceUgDZe.jpg</Image>
		</Person>
		<Person>
			<Name>Deni Gordon</Name>
			<Type>Actor</Type>
			<Role>Priestess</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/5TQlwo1T3EnORzkmLQMKaDZCvpa.jpg</Image>
		</Person>
		<Person>
			<Name>Rowan Witt</Name>
			<Type>Actor</Type>
			<Role>Spoon Boy</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/kJot5sckPZRFVzkKEEJtaod423s.jpg</Image>
		</Person>
		<Person>
			<Name>Eleanor Witt</Name>
			<Type>Actor</Type>
			<Role>Potential</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/7lo8gg0j6OLzuAqXg1giQWAsY4F.jpg</Image>
		</Person>
		<Person>
			<Name>Tamara Brown</Name>
			<Type>Actor</Type>
			<Role>Potential</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/Y6PpJtEFlCPbb2Vn0ubjTPjCtr.jpg</Image>
		</Person>
		<Person>
			<Name>Janaya Pender</Name>
			<Type>Actor</Type>
			<Role>Potential</Role>
			<Image />
		</Person>
		<Person>
			<Name>Adryn White</Name>
			<Type>Actor</Type>
			<Role>Potential</Role>
			<Image />
		</Person>
		<Person>
			<Name>Natalie Tjen</Name>
			<Type>Actor</Type>
			<Role>Potential</Role>
			<Image />
		</Person>
		<Person>
			<Name>Bill Young</Name>
			<Type>Actor</Type>
			<Role>Lieutenant</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/1B3amfg9o97EurkYl9BAlXZPC60.jpg</Image>
		</Person>
		<Person>
			<Name>David O'Connor</Name>
			<Type>Actor</Type>
			<Role>FedEx Man</Role>
			<Image />
		</Person>
		<Person>
			<Name>Jeremy Ball</Name>
			<Type>Actor</Type>
			<Role>Businessman</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/o81K9lM34FbCxwHakzXdtIM1JP9.jpg</Image>
		</Person>
		<Person>
			<Name>Fiona Johnson</Name>
			<Type>Actor</Type>
			<Role>Woman In Red</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/tdbzgopHXZMpiLNt64TuLhsPlPA.jpg</Image>
		</Person>
		<Person>
			<Name>Harry Lawrence</Name>
			<Type>Actor</Type>
			<Role>Old Man</Role>
			<Image />
		</Person>
		<Person>
			<Name>Steve Dodd</Name>
			<Type>Actor</Type>
			<Role>Blind Man</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/30pDtMIblGP1yDsFUaT5p0FJL1L.jpg</Image>
		</Person>
		<Person>
			<Name>Luke Quinton</Name>
			<Type>Actor</Type>
			<Role>Security Guard</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/9W6abwKWcCCu4FHtQZuWvOb2MBP.jpg</Image>
		</Person>
		<Person>
			<Name>Lawrence Woodward</Name>
			<Type>Actor</Type>
			<Role>Guard</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/dAcZMeJmn5WzdD9SdAHGDlDq7CO.jpg</Image>
		</Person>
		<Person>
			<Name>Michael Butcher</Name>
			<Type>Actor</Type>
			<Role>Cop Who Captures Neo</Role>
			<Image />
		</Person>
		<Person>
			<Name>Bernard Ledger</Name>
			<Type>Actor</Type>
			<Role>Big Cop</Role>
			<Image />
		</Person>
		<Person>
			<Name>Robert Simper</Name>
			<Type>Actor</Type>
			<Role>Cop</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/8lBlkhZlTBfkIi6i0iWugZaiIkY.jpg</Image>
		</Person>
		<Person>
			<Name>Chris Pattinson</Name>
			<Type>Actor</Type>
			<Role>Cop</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/aB6AlYxCtiSydRpaHpnyf2mLCVw.jpg</Image>
		</Person>
		<Person>
			<Name>Nigel Harbach</Name>
			<Type>Actor</Type>
			<Role>Parking Cop</Role>
			<Image>https://image.tmdb.org/t/p/w300_and_h450_bestv2/ugpQA7MIoEZty4WB2l0uqTRniBy.jpg</Image>
		</Person>
	</Persons>
	<Awards>Won 4 Oscars. Another 37 wins &amp; 49 nominations.</Awards>
	<BackdropURL>http://image.tmdb.org/t/p/original/7u3pxc0K1wx32IleAkLv78MKgrw.jpg</BackdropURL>
	<Director>Lana Wachowski</Director>
	<FullCertifications>Argentina:13, Australia:M, Belgium:KT/EA, Brazil:12, Brazil:14, Canada:14A, Canada:PA, Canada:14, Canada:AA, Canada:13+, Denmark:15, Finland:K-16, France:Tous publics, Germany:16, Hong Kong:IIB, Hungary:16, Iceland:16, India:A, Ireland:15, Ireland:18, Israel:PG, Italy:T, Japan:PG-12, Malaysia:18SG, Mexico:B, Netherlands:16, New Zealand:M, Norway:15, Peru:14, Philippines:PG-13, Portugal:M/12, Russia:16+, Singapore:PG, Singapore:PG13, South Africa:10, South Korea:12, Spain:18, Sweden:15, Switzerland:12, Switzerland:12, United Kingdom:15, United States:R</FullCertifications>
	<FormalMPAA>Rated R for sci-fi violence and brief language</FormalMPAA>
	<Votes>1450282</Votes>
	<Synopsis>Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.</Synopsis>
	<Plot>Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.</Plot>
	<Outline>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</Outline>
	<ShortDescription>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</ShortDescription>
	<PosterURL>http://image.tmdb.org/t/p/original/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg</PosterURL>
	<Tagline>Welcome to the Real World.</Tagline>
	<Taglines>
		<Tagline>Welcome to the Real World.</Tagline>
	</Taglines>
	<Top250></Top250>
	<TrailerURL>http://www.youtube.com/watch?v=m8e-FF8MsqU</TrailerURL>
	<Website>http://www.warnerbros.com/matrix</Website>
	<ReleaseDate>1999-03-30</ReleaseDate>
	<WritersList>Lilly Wachowski|Lana Wachowski</WritersList>
	<Popularity>23.045</Popularity>
	<VoteCount>12733</VoteCount>
	<TMDbCollectionId>2344</TMDbCollectionId>
	<CollectionNumber>2344</CollectionNumber>
	<CollectionName>The Matrix</CollectionName>
	<Tags>
		<Tag>saving the world</Tag>
		<Tag>artificial intelligence</Tag>
		<Tag>man vs machine</Tag>
		<Tag>philosophy</Tag>
		<Tag>prophecy</Tag>
		<Tag>martial arts</Tag>
		<Tag>self sacrifice</Tag>
		<Tag>fight</Tag>
		<Tag>insurgence</Tag>
		<Tag>virtual reality</Tag>
		<Tag>dystopia</Tag>
		<Tag>truth</Tag>
		<Tag>cyberpunk</Tag>
		<Tag>dream world</Tag>
		<Tag>messiah</Tag>
		<Tag>gnosticism</Tag>
		<Tag>trans director</Tag>
	</Tags>
	<SimilarMovies>
		<SimilarMovie>The Matrix Revolutions</SimilarMovie>
		<SimilarMovie>The Matrix Reloaded</SimilarMovie>
		<SimilarMovie>Terminator Salvation</SimilarMovie>
		<SimilarMovie>The Terminator</SimilarMovie>
		<SimilarMovie>Terminator 3: Rise of the Machines</SimilarMovie>
		<SimilarMovie>Blade Runner</SimilarMovie>
		<SimilarMovie>Terminator Genisys</SimilarMovie>
		<SimilarMovie>Upgrade</SimilarMovie>
		<SimilarMovie>Blade Runner 2049</SimilarMovie>
		<SimilarMovie>Ghost in the Shell</SimilarMovie>
		<SimilarMovie>A.I. Artificial Intelligence</SimilarMovie>
		<SimilarMovie>I, Robot</SimilarMovie>
		<SimilarMovie>I Am Legend</SimilarMovie>
		<SimilarMovie>Kill Bill: Vol. 1</SimilarMovie>
		<SimilarMovie>Escape from New York</SimilarMovie>
		<SimilarMovie>Automata</SimilarMovie>
		<SimilarMovie>Inception</SimilarMovie>
		<SimilarMovie>Ready Player One</SimilarMovie>
		<SimilarMovie>Ghost in the Shell</SimilarMovie>
		<SimilarMovie>Interstellar</SimilarMovie>
	</SimilarMovies>
	<OtherID_RottenTomatoes></OtherID_RottenTomatoes>
	<RottenTomatoesId></RottenTomatoesId>
	<CriticRating></CriticRating>
	<CriticRatingSummary></CriticRatingSummary>
	<IMDB_ID>tt0133093</IMDB_ID>
	<TMDB>603</TMDB>
	<TMDB_ID>603</TMDB_ID>
	<Rating>8.7</Rating>
	<certification>R</certification>
	<Trailer>http://www.youtube.com/watch?v=m8e-FF8MsqU</Trailer>
	<Runtime>136</Runtime>
	<Description>A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</Description>
	<PremiereDate>1999-03-30</PremiereDate>
	<VideoAspect>2.35:1</VideoAspect>
	<VideoBitrate>36852000</VideoBitrate>
	<VideoCodec>HEVC</VideoCodec>
	<VideoCodecType>HEVC</VideoCodecType>
	<VideoCodecRaw>HEVC</VideoCodecRaw>
	<VideoFileSize>37675795874</VideoFileSize>
	<VideoHeight>1600</VideoHeight>
	<VideoLength>136</VideoLength>
	<VideoLengthSeconds>8179</VideoLengthSeconds>
	<VideoQuality>Superior (4K UHD)</VideoQuality>
	<VideoWidth>3840</VideoWidth>
	<AudioBitrate>0</AudioBitrate>
	<AudioChannels>7.1</AudioChannels>
	<AudioCodec>TRUEHD</AudioCodec>
	<AudioCodecRaw>TRUEHD</AudioCodecRaw>
	<AudioFrequency>48000</AudioFrequency>
	<AspectRatio>2.40:1</AspectRatio>
	<MediaInfo>
		<Video>
			<Codec>HEVC</Codec>
			<FFCodec>HEVC</FFCodec>
			<BitRate>36852000</BitRate>
			<Height>1600</Height>
			<Width>3840</Width>
			<FrameRate>23.976</FrameRate>
			<Duration>136</Duration>
			<DurationSeconds>8179</DurationSeconds>
			<ScanType>Progressive</ScanType>
		</Video>
		<Audio>
			<Codec>TRUEHD</Codec>
			<FFCodec>TRUEHD</FFCodec>
			<Channels>8</Channels>
			<BitRate>0</BitRate>
			<Language>eng</Language>
		</Audio>
	</MediaInfo>
	<VideoHasSubtitles>True</VideoHasSubtitles>
	<Type></Type>
</Title>
```

**Comment by concastelo** [comment]
I see the issue as well. I've ripped my own UHD audio is Atmos (TrueHD) and video bitrate is well over 50Mbps but quality shows 53. I noticed the XML tag <VideoQuality> does contains "Superior (4K UHD)".

Running 2.19 build 7819.742

	<Type>Blu-Ray</Type>
	<VideoAspect>16:9</VideoAspect>
	<VideoBitrate>52701000</VideoBitrate>
	<VideoCodec>HEVC</VideoCodec>
	<VideoCodecType>HEVC</VideoCodecType>
	<VideoCodecRaw>HEVC</VideoCodecRaw>
	<VideoFileSize>61636757740</VideoFileSize>
	<VideoHeight>2160</VideoHeight>
	<VideoLength>143</VideoLength>
	<VideoLengthSeconds>8599</VideoLengthSeconds>
	<VideoQuality>Superior (4K UHD)</VideoQuality>
	<VideoWidth>3840</VideoWidth>
	<AudioBitrate>3579349</AudioBitrate>
	<AudioChannels>7.1</AudioChannels>
	<AudioCodec>TRUEHD</AudioCodec>
	<AudioCodecRaw>TRUEHD</AudioCodecRaw>
	<AudioFrequency>48000</AudioFrequency>
	<AspectRatio>1.78:1</AspectRatio>
	<MediaInfo>
		<Video>
			<Codec>HEVC</Codec>
			<FFCodec>HEVC</FFCodec>
			<BitRate>52701000</BitRate>
			<Height>2160</Height>
			<Width>3840</Width>
			<FrameRate>23.976</FrameRate>
			<Duration>143</Duration>
			<DurationSeconds>8599</DurationSeconds>
			<ScanType>Progressive</ScanType>
		</Video>
		<Audio>
			<Codec>TRUEHD</Codec>
			<FFCodec>TRUEHD</FFCodec>
			<Channels>8</Channels>
			<BitRate>3579349</BitRate>
			<Language>eng</Language>
		</Audio>
	</MediaInfo>
